version: latest

services:
  database:
    image: postgres:alpine
    container_name: ${DATABASE_CONTAINER_NAME}
    volumes:
      - ${PROJECT_DATA_DIR}/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env

  application:
    build: .
    container_name: ${APPLICATION_CONTAINER_NAME}
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - ${APPLICATION_PORT}:8000
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      # avoid output buffering for realtime logging
      PYTHONUNBUFFERED: 1
    depends_on:
      - database
