openapi: 3.0.3
info:
  title: Chained Notes API
  version: 1.0.0
  description: An application for chained notes.
paths:
  /api/notes/:
    get:
      operationId: api_notes_list
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Note"
          description: ""
    post:
      operationId: api_notes_create
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteRequest"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/NoteRequest"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/NoteRequest"
        required: true
      security:
        - jwtAuth: []
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
          description: ""
  /api/notes/{id}/:
    get:
      operationId: api_notes_retrieve
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: A unique integer value identifying this note.
          required: true
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
          description: ""
    put:
      operationId: api_notes_update
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: A unique integer value identifying this note.
          required: true
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteRequest"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/NoteRequest"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/NoteRequest"
        required: true
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
          description: ""
    patch:
      operationId: api_notes_partial_update
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: A unique integer value identifying this note.
          required: true
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchedNoteRequest"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/PatchedNoteRequest"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/PatchedNoteRequest"
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
          description: ""
    delete:
      operationId: api_notes_destroy
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: A unique integer value identifying this note.
          required: true
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "204":
          description: No response body
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        body:
          type: string
      required:
        - body
        - id
        - title
    NoteRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        body:
          type: string
          minLength: 1
      required:
        - body
        - title
    PatchedNoteRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        body:
          type: string
          minLength: 1
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
