name: Check code

on:
  pull_request:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6

      - name: Install poetry
        run: pip install poetry

      - name: Install poetry dependencies
        run: poetry install

      - uses: actions/setup-node@v5

      - name: Install npm dependencies
        run: npm install

      - name: Check code format
        run: make check-format

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Lint code
        run: make lint

  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check types
        run: make check-types

  check-openapi-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - uses: actions/setup-node@v5

      - name: Install npm dependencies
        run: npm install

      - name: Check if OpenAPI schema is up to date
        run: make check-openapi-schema

  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check migrations
        run: make check-migrations
