name: Build and push a branch image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

# TODO: add multiplatform images: https://docs.docker.com/build/ci/github-actions/multi-platform/
# TODO: use docker build cache: https://docs.docker.com/build/cache/backends/
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/msga-mmm/chained-notes
          tags: |
            type=raw,value=dev-${{ github.head_ref }}-{{sha}}
            type=raw,value=dev-{{date 'YYYYMMDD-hhmmss'}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
